# Generated by Django 4.2.7 on 2025-09-28 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertnotification",
            name="related_disease_case",
        ),
        migrations.RemoveField(
            model_name="alertnotification",
            name="related_health_report",
        ),
    ]
