services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 health_surveillance.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-change-this-in-production-very-long-random-string-here
      DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.1.5,0.0.0.0"
      SPATIALITE_LIBRARY_PATH: mod_spatialite
      REDIS_URL: redis://redis:6379/0
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: dhaked.7248@gmail.com
      EMAIL_HOST_PASSWORD: "ihpd pwrf vldy ntbf"
      TWILIO_ACCOUNT_SID: AC04bd70da4acea4bc586b30fd0a06460b
      TWILIO_AUTH_TOKEN: 6ea6b18f18c43747b6630ea334d81c13
      TWILIO_PHONE_NUMBER: "+16812026553"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    command: celery -A health_surveillance worker --loglevel=info
    volumes:
      - .:/app
    environment:
      SECRET_KEY: django-insecure-change-this-in-production-very-long-random-string-here
      DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.1.5,0.0.0.0"
      SPATIALITE_LIBRARY_PATH: mod_spatialite
      REDIS_URL: redis://redis:6379/0
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: dhaked.7248@gmail.com
      EMAIL_HOST_PASSWORD: "ihpd pwrf vldy ntbf"
      TWILIO_ACCOUNT_SID: AC04bd70da4acea4bc586b30fd0a06460b
      TWILIO_AUTH_TOKEN: 6ea6b18f18c43747b6630ea334d81c13
      TWILIO_PHONE_NUMBER: "+16812026553"
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A health_surveillance beat --loglevel=info
    volumes:
      - .:/app
    environment:
      SECRET_KEY: django-insecure-change-this-in-production-very-long-random-string-here
      DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.1.5,0.0.0.0"
      SPATIALITE_LIBRARY_PATH: mod_spatialite
      REDIS_URL: redis://redis:6379/0
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: dhaked.7248@gmail.com
      EMAIL_HOST_PASSWORD: "ihpd pwrf vldy ntbf"
      TWILIO_ACCOUNT_SID: AC04bd70da4acea4bc586b30fd0a06460b
      TWILIO_AUTH_TOKEN: 6ea6b18f18c43747b6630ea334d81c13
      TWILIO_PHONE_NUMBER: "+16812026553"
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  redis_data:
  static_volume:
  media_volume: